### ISSUE TITLE
1012 connections in time max

### ISSUE THREAD

**Issue by marinakr** [esl/escalus#133]
I am tring to use escalus for load testing
Start:
erl -pa ebin deps/*/ebin -P 50000  -cookie 'somecookie'

trying to connect users :
lists:map(fun(X) ->
    User =
      iolist_to_binary([<<"0">>, integer_to_list(X)]),
    F = [{username, User},
      {server,<<"myserver">>},
      {host,<<"myserver.com">>},
      {port,5222},
      {auth,{escalus_auth,auth_plain}},
      {wspath,undefined},
      {username,User},
      {server,<<"myserver">>},
      {host,<<"myserver.com">>},
      {password,<<"p1">>},
      {starttls,true}],
    timer:sleep(50), %arrival time
    erlang:Fun(escalus_connection, start, [F])
            end,
    lists:seq(1, 5000, 1))

No matter there are 5000 or 3000 or  after 1012 I don't see any tries to connect on server log
If I start escalus parralel in new tab in console, I can connect 2000,3000

**Comment by michalwski** [comment]
Could you match (or log) the result of `escalus_connection:start`? After 1012 you should start seeing some errors. Hopefully the reason will be meaningful.

**Comment by marinakr** [comment]
The problem is it matches {ok, _,_,_} = start(..

**Comment by michalwski** [comment]
If `escalus_connection:start` connects to the server the result will be indeed `{ok, _, _, _}`. If there is any error the result will be different with some reason describing what was wrong. It's possible that it will take some time to return the error, due to waiting for a response from the server, f.e.

**Comment by michalwski** [comment]
I've just noticed you are using `{starttls, true}`. Did you try setting it to false? Chances are that TLS causes the problem.

**Comment by marinakr** [comment]
Server requies tls
maybe problem in ulimits, I will check and update

**Comment by michalwski** [comment]
Could be. Didn't think about it at first because you said that with more tabs you can do more connections. But after another thought, this makes sense. You probably have default file limit which is 1024 and for new tabs you get new 1024 files to open.

**Comment by marinakr** [comment]
My fault. I should set ulimits before open issue

**Comment by michalwski** [comment]
That's not your fault :) Thanks for contacting us. Feel free to get back to us with question if you have some. Also since you are load testing with escalus, did you see https://github.com/esl/amoc? This is a very simple tool which helps to run load tests. There are some example scenarios (using escalus).

**Comment by marinakr** [comment]
I didn't know about amoc, the most popular google result is tsung, but tsung is not suitable
Will check it
